"""
Document Q&A Web App with Closed-Source LLM (Google Gemini 2.0 Flash)
Author: Maryna Basalay

This Streamlit application allows a user to:
• Upload a document (TXT, PDF, DOCX, HTML)
• Extract text from the document
• Ask a question about the document
• Receive an answer generated by the Gemini 2.0 Flash LLM

How to run the app:

1) Install required Python packages:
   pip install -r requirements.txt

2) Get a free Gemini API key from:
   https://ai.google.dev/gemini-api

3) Run the Streamlit app:
   streamlit run document_qa_llm_app.py
"""

import streamlit as st
import tempfile
import fitz
import docx2txt
from bs4 import BeautifulSoup
from google import genai


def load_text_from_file(file):
    """
    Load text from an uploaded file (txt, pdf, docx, html)
    and return extracted plain text.
    """

    filename = file.name.lower()

    # Save uploaded file to a temporary path
    with tempfile.NamedTemporaryFile(delete=False) as tmp:
        tmp.write(file.read())
        temp_path = tmp.name

    # TXT
    if filename.endswith(".txt"):
        with open(temp_path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()

    # PDF
    if filename.endswith(".pdf"):
        text = ""
        pdf_document = fitz.open(temp_path)

        for page in pdf_document:
            text += page.get_text() + "\n"

        return text

    # DOCX
    if filename.endswith(".docx"):
        return docx2txt.process(temp_path)

    # HTML
    if filename.endswith(".html") or filename.endswith(".htm"):
        with open(temp_path, "r", encoding="utf-8", errors="ignore") as f:
            html_content = f.read()

        soup = BeautifulSoup(html_content, "html.parser")
        return soup.get_text(separator="\n")

    return ""


st.title("Document Q&A with Gemini LLM")

st.write(
    "Upload a document and ask a question. "
    "The app extracts text from the file and sends the context to the Gemini LLM."
)


# User enters their own API key at runtime (not stored in code)
gemini_api_key = st.text_input(
    "Enter your Gemini API key:",
    type="password"
)

st.caption(
    "You can obtain a free API key from Google AI Studio: https://ai.google.dev/gemini-api"
)


question = st.text_input("Enter your question:")

uploaded_file = st.file_uploader(
    "Upload a document (optional):",
    type=["txt", "pdf", "docx", "html"]
)


if st.button("Ask"):

    if not gemini_api_key:
        st.error("Please enter your Gemini API key.")

    elif not question.strip():
        st.error("Please enter a question.")

    else:

        # Extract document context
        if uploaded_file is not None:
            context_text = load_text_from_file(uploaded_file)
        else:
            context_text = ""

        # Initialize Gemini client
        client = genai.Client(api_key=gemini_api_key)

        # Build prompt
        prompt = f"""
Context from document (may be empty):

{context_text}

Question:
{question}

Answer clearly and use the document context when relevant.
"""

        try:

            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt
            )

            st.subheader("AI Response")
            st.write(response.text)

        except Exception as e:

            st.error(f"Error while calling Gemini API: {e}")
